# Generated by Django 6.0.4 on 2026-05-04 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_brand_product_ean_product_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='options',
            field=models.JSONField(blank=True, help_text='Beschikbare opties (bijv. kleur)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Inkoopprijs excl. BTW', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Adviesprijs incl. BTW', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, help_text='Productdetails en eigenschappen', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_status',
            field=models.CharField(blank=True, help_text='Beschikbaarheid/Levertijd', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ean',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='original_url',
            field=models.URLField(max_length=1000, unique=True),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.product')),
            ],
        ),
    ]
